trigger:
- master  # Replace with your branch name

pool:
  vmImage: 'ubuntu-latest'



steps:
- script: echo 'Starting Maven build'
  displayName: 'Maven Build'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'

- script: echo 'Running SonarQube analysis'
  displayName: 'SonarQube Analysis'

- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'mysonarsvc'

- task: SonarQubeAnalyze@4

- script: echo 'Building and Pushing Docker image'
  displayName: 'Docker Build & Push'

- task: Docker@2
  inputs:
    containerRegistry: 'mydockersvcsonar'
    repository: 'mysonarquberepo'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- script: echo 'Build completed!'
  displayName: 'Build Completed'
