trigger:
- master  # Replace with your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: MavenAuthenticate@0
  inputs:
    mavensettingsfile: 'settings.xml'  # Path to your Maven settings.xml file
    publishmavenartifacts: false
    mavenPomFile: 'pom.xml'  # Path to your Maven project POM file
    goals: 'clean install'
