trigger:
- master



pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: BuildJob
    steps:
    - task: UseJavaVersion@0
      inputs:
        version: '11' # Set the Java version you need

    - script: echo 'Starting Maven build'
      displayName: 'Maven Build'
      workingDirectory: $(System.DefaultWorkingDirectory)

    - script: mvn clean install -DskipTests=true
      displayName: 'Maven Package'
      workingDirectory: $(System.DefaultWorkingDirectory)

    - script: echo 'Running SonarQube analysis'
      displayName: 'SonarQube Analysis'
      workingDirectory: $(System.DefaultWorkingDirectory)

    - task: SonarQubePrepare@4
      inputs:
        SonarQube: 'mydockersvcsonar' # Replace with your SonarQube service connection

    - task: SonarQubeAnalyze@4

    - script: echo 'Building Docker image'
      displayName: 'Docker Build'
      workingDirectory: $(System.DefaultWorkingDirectory)

    - task: Docker@2
      inputs:
        containerRegistry: 'mydockersvcsonar' # Replace with your Docker Hub service connection
        repository: 'mysonarsvc'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'

    - script: echo 'Pushing Docker image to Docker Hub'
      displayName: 'Docker Push'
      workingDirectory: $(System.DefaultWorkingDirectory)

    - task: Docker@2
      inputs:
        containerRegistry: 'shakirdocker'
        repository: 'shakirdocker/mysonarquberepo'
        command: 'push'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'
