trigger:
- master  # You can adjust this to match your branch

pool:
  vmImage: 'ubuntu-latest'

steps:


- script: 'mvn clean install'
  displayName: 'Maven Build'

- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'YourSonarQubeServiceConnection'  # Configure your SonarQube service connection
    scannerMode: 'CLI'
    projectKey: 'sonarqubeprojectkey'
    projectName: 'mysonarqube'
    extraProperties: |
      sonar.java.source=11  # Specify your Java version

- script: 'mvn sonar:sonar'
  displayName: 'Run SonarQube Analysis'

- task: Docker@2
  inputs:
    containerRegistry: 'mydockersvcsonar'  # Configure your DockerHub service connection
    repository: 'shakirdocker/mysonarquberepo'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: 'latest'

- script: |
    kubectl apply -f kubernetes/deployment.yaml  # Apply your Kubernetes deployment YAML
    kubectl apply -f kubernetes/service.yaml     # Apply your Kubernetes service YAML
  displayName: 'Deploy to AKS'
